post_install() {
    sed -e "s|ID=manjaro|ID=netrunner|" \
        -e "s|Manjaro Linux|Netrunner Rolling|g" \
        -e "s|https://www.manjaro.org/|http://www.netrunner.com/|g" \
        -e "s|https://bugs.manjaro.org/|http://forums.netrunner.com/|g" \
        -e '/ID=netrunner/a\BUILD_ID=2017.07' \
        -i usr/lib/os-release
}

post_remove() {
    sed -e "s|ID=netrunner|ID=manjaro|" \
        -e "s|Netrunner Rolling|Manjaro Linux|g" \
        -e "s|http://www.netrunner.com/|https://www.manjaro.org/|g" \
        -e "s|http://forums.netrunner.com/|https://bugs.manjaro.org/|g" \
        -e '/BUILD_ID=2017.07/d' \
        -i usr/lib/os-release
}
